# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Awesome README
site_url: https://github.com/matiassingers/awesome-readme
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: matiassingers/awesome-readme
repo_url: https://github.com/matiassingers/awesome-readme
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects

extra_css:
  - css/neoteroi-mkdocs.css

# Theme
theme:
  name: material
  language: es
  logo: images/awesome2.png
  favicon: images/awesome2.png
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matiassingers
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/matiassingers
    - icon: fontawesome/solid/globe
      link: https://mts.io/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#TOC
nav:
    - Home: index.md
    - examples.md
    - articles.md
    - tools.md
    - others.md
